org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Fix for "Daemon compilation failed: null"
kotlin.daemon.jvmargs=-Xmx4G -Dkotlin.daemon.client.alive.path="kotlin_daemon_alive"
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
